DROP TABLE IF EXISTS `tbl_trx_order`;

CREATE TABLE `tbl_trx_order` (
    `id` VARCHAR(32) NOT NULL PRIMARY KEY,
    `merchant_name` VARCHAR(50),
    `amount` DECIMAL(11, 2),
    `tax_rate` DECIMAL(11, 4),
    `charge` DECIMAL(11, 2),
    `actual_amount` DECIMAL(11, 2),
    `order_serial_num` VARCHAR(100),
    `merchant_serial_num` VARCHAR(100),
    `batch_no` VARCHAR(50),
    `payment_voucher` VARCHAR(255),
    `payee_name` VARCHAR(255),
    `payee_mobile` VARCHAR(255),
    `payee_bank_card` VARCHAR(255),
    `bank_name` VARCHAR(255),
    `payee_id_card_no` VARCHAR(255),
    `order_status` INTEGER,
    `batch_payment_record_id` VARCHAR(32),
    `payment_channel` VARCHAR(15),
    `merchant_id` INTEGER,
    `dna` VARCHAR(100),
    `trx_no` VARCHAR(64) NOT NULL,
    `comment` VARCHAR(255),
    `subject_conscription` VARCHAR(20),
    `error_code` VARCHAR(16),
    `provider_id` INTEGER,
    `fillup_charge_type` VARCHAR(16),
    `fillup_charge` DECIMAL(11, 2),
    `error_msg` VARCHAR(256),
    `create_time` TIMESTAMP,
    `update_time` TIMESTAMP,
    `original_trx_no` VARCHAR(100),
    `subrogate_id` VARCHAR(32),
    `payee_name_dec` VARCHAR(50),
    `payee_mobile_dec` VARCHAR(50),
    `payee_bank_card_dec` VARCHAR(50),
    `payee_id_card_no_dec` VARCHAR(50),
    `personal_rate` DECIMAL(11, 4),
    `company_rate` DECIMAL(11, 4),
    `fillup_fee_bears` INTEGER,
    `personal_charge` DECIMAL(11, 2),
    `company_charge` DECIMAL(11, 2),
    `task_user_id` CHAR(32),
    `receive_status` VARCHAR(16),
    `task_id` VARCHAR(32),
    `trade_mode` VARCHAR(16),
    `real_subrogate_id` VARCHAR(32),
    `real_subrogate` VARCHAR(50),
    `transfer_fee` DECIMAL(10, 2),
    `task_order_id` VARCHAR(50),
    `mission_name` VARCHAR(50),
    `task_number` VARCHAR(50),
    `actual_charge` DECIMAL(11, 2),
    `actual_fillup_charge` DECIMAL(11, 2),
    `belong_agent_id` BIGINT,
    `super_agent_id` BIGINT,
    `top_agent_id` BIGINT,
    `quota_type` INTEGER,
    `actual_tax_rate` DECIMAL(11, 4),
    `complete_date_time` TIMESTAMP,
    `invoke_mode` VARCHAR(10),
    `bank_serial_num` VARCHAR(64),
    `bank_fund_serial_num` VARCHAR(64),
    `transfer_scene_report_info` VARCHAR(255),
    `app_id` VARCHAR(32),
    `person_tax_amount` DECIMAL(11, 2),
    `channel_rate` DECIMAL(11, 4),
    `channel_fee` DECIMAL(11, 4)
);
